# A Sun and Moon Azimuth Tracker
# All the updates to the azimuth positions are made by the Home Assistant SunMoonAutomation

substitutions:
  nodename: SunMoonAz

  # pin assignments
  servo_sun_azimuth: GPIO19
  servo_moon_azimuth: GPIO21

esphome:
  name: $nodename
  friendly_name: $nodename

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.0.110
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0
  #
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $nodename
    password: !secret wifi_password

captive_portal:

binary_sensor:
  - platform: status
    name: Status

button:
  - platform: restart
    name: Restart

  - platform: shutdown
    name: shutdown

number:
  # Define a number template to control servo 1
  # servo 1 is sun azimuth: 0 to 360: map to -1 to +1
  - platform: template
    name: Sun Azimuth Number
    id: number_sun_azimuth
    optimistic: True
#    internal: True
    mode: slider
    min_value: 0
    initial_value: 180
    max_value: 360
    step: 0.1
    set_action:
      then:
        - servo.write:
            id: servo_sun_azimuth
            level: !lambda 'return ((x / 360.0)* 2.0) - 1.0;'

  # Define a number template to control servo 2
  # servo 2 is moon azimuth: 0 to 360: map to -1 to +1
  - platform: template
    name: Moon Azimuth Number
    id: number_moon_azimuth
    optimistic: true
#    internal: True
    mode: slider
    min_value: 0
    initial_value: 180
    max_value: 360
    step: 0.1
    set_action:
      then:
        - servo.write:
            id: servo_moon_azimuth
            level: !lambda 'return ((x / 360.0)* 2.0) - 1.0;'

output:
  # Servo output 1   
  - platform: ledc
    pin: ${servo_sun_azimuth}
    id: ledc_1
    channel: 0
    frequency: 50 Hz

  # Servo output 2
  - platform: ledc
    pin: ${servo_moon_azimuth}
    id: ledc_2
    channel: 1
    frequency: 50 Hz

servo:
    # servo 1
  - id: servo_sun_azimuth
    output: ledc_1
    auto_detach_time: 50ms
    transition_length: 8s

    # servo 2
  - id: servo_moon_azimuth
    output: ledc_2
    auto_detach_time: 50ms
    transition_length: 8s
